name: Build Spring Boot App

on: [push]

jobs:
  build-backend:
    name: Build Backend
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout le code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build avec Maven
        run: mvn clean install

      - name: Upload JAR comme artifact
        uses: actions/upload-artifact@v4
        with:
          name: springboot-app
          path: backend/target/*.jar
